name: "Deploy to Retinbox Web Hosting"
description: "GitHub Action to deploy your website to Retinbox Web Hosting"
author: "Retinbox"

inputs:
  site:
    description: "The site to be deployed"
    required: false
  build:
    description: "The build command"
    required: false
  outdir:
    description: "The output directory"
    required: false

env:
  RTH_API_KEY:
    description: "The Retinbox API key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: "Deploy to Retinbox Web Hosting"
      run: |
        ARGS=()
        [[ -n "${{ inputs.site }}" ]] && ARGS+=(--site "${{ inputs.site }}")
        [[ -n "${{ inputs.build }}" ]] && ARGS+=(--build "${{ inputs.build }}")
        [[ -n "${{ inputs.outdir }}" ]] && ARGS+=(--outdir "${{ inputs.outdir }}")
        deno -Ar https://host.retiehe.com/cli "${ARGS[@]}"
      shell: bash
      env:
        RTH_API_KEY: ${{ env.RTH_API_KEY }}
